### ISSUE TITLE
Add notes/bubbles with studybears on the side

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/website#35]
It'd be nice to have some themed conversations between the characters: studybears, the cat... with a more game-like design. The idea is to have them bring different points of views on tutorials and to have gamy visuals. The developer, the artist, and the designer who are trying to solve problems, and the cat that messes up the project and pin-points issues or asks tricky questions.

They'll also serve for videos

- [ ] design a visual mockup
- [ ] design characters as game-style sprites in Krita
- [ ] implement speech box bubbles in css

**Comment by NathanLovato** [comment]
```css
.speech-bubble { position: relative; background: #00aabb; border-radius: .4em; } .speech-bubble:after { content: ''; position: absolute; left: 0; top: 80%; width: 0; height: 0; border: 30px solid transparent; border-right-color: #00aabb; border-left: 0; border-bottom: 0; margin-left: -30px; }
```
